openapi: "3.0.2"
info:
  title: xbVorrat API
  version: "1.1.0"
  description: |
    Die API für xbVorrat ermöglicht die Verwaltung von zu bevorratenden Gegenständen in Lagerboxen.

    ### Änderungen
    Version | Beschreibung
    --------|-------------
    1.0.0   | Initiale Version
    1.1.0   | Der Endpunkt /stocks/rich wird zurück gebaut, die Funktionalität wird in der GET-Methode von /stocks integriert. Ein zusätzlicher query-Parameter zur Sortierung wurde hinzugefügt.
servers:
  - url: http://localhost:8081/api
paths:
  /health:
    get:
      tags:
        - Test-API
      summary: "Ein simpler health-check"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: integer
                    minimum: 1
  /boxes:
    get:
      tags:
        - Boxen verwalten
      summary: "Eine Liste aller angelegten Boxen. Wenn keine Boxen angelegt sind, wird null zurück gegeben."
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BoxID"
    put:
      tags:
        - "Boxen verwalten"
      summary: Anlegen einer neuen Box.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Box"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BoxID"
        "400":
          $ref: "#/components/responses/400"
  /boxes/{id}:
    patch:
      tags:
        - "Boxen verwalten"
      summary: Änderungen am Namen oder der Notiz einer Box.
      parameters:
        - name: id
          in: path
          description: Die Id der zu ändernden Box
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Box"
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
    delete:
      tags:
        - "Boxen verwalten"
      summary: Löschen einer Box.
      parameters:
        - name: id
          in: path
          description: Die Id der zu löschenden Box
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "403":
          description: Forbidden - Die Box kann nicht gelöscht werden. Sie wird noch verwendet.
        "404":
          $ref: "#/components/responses/404"
  /units:
    get:
      tags:
        - "Einheiten verwalten"
      summary: Eine Liste aller angelegten Einheiten. Wenn keine Einheiten angelegt sind, null zurück gegeben.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UnitID"
    put:
      tags:
        - "Einheiten verwalten"
      summary: Anlegen einer neuen Einheit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Unit"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnitID"
        "400":
          $ref: "#/components/responses/400"
  /units/{id}:
    patch:
      tags:
        - "Einheiten verwalten"
      summary: Änderungen einer Einheit oder ihres Langtextes.
      parameters:
        - name: id
          in: path
          description: Die Id der zu ändernden Einheit
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Unit"
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
    delete:
      tags:
        - "Einheiten verwalten"
      summary: Löschen einer Einheit.
      parameters:
        - name: id
          in: path
          description: Die Id der zu löschenden Einheit
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
  /articles:
    get:
      tags:
        - Artikel verwalten
      summary: "Eine Liste aller angelegten Artikel. Wenn keine Artikel angelegt sind, wird null zurück gegeben."
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArticleID"
    put:
      tags:
        - "Artikel verwalten"
      summary: Anlegen eines neuen Artikels.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArticleID"
        "400":
          $ref: "#/components/responses/400"
        "409":
          $ref: "#/components/responses/409Article"
  /articles/{id}:
    patch:
      tags:
        - "Artikel verwalten"
      summary: Änderungen eines Artikels oder seiner Einheit.
      parameters:
        - name: id
          in: path
          description: Die Id des zu ändernden Artikels
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "409":
          $ref: "#/components/responses/409Article"
    delete:
      tags:
        - "Artikel verwalten"
      summary: Löschen eines Artikels.
      parameters:
        - name: id
          in: path
          description: Die Id des zu löschenden Artikels
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "403":
          description: Forbidden - Dieser Artikel kann nicht gelöscht werden. Er ist noch in Verwendung.
        "404":
          $ref: "#/components/responses/404"
  /stocks:
    get:
      tags:
        - Vorräte verwalten
      summary: "Eine Liste aller angelegten Vorräte. Wenn keine Vorräte angelegt sind, wird null zurück gegeben."
      parameters:
        - in: query
          name: sort 
          schema:
            type: string
            default: id
            enum:
              - id
              - articlestr
              - boxstr
              - expiry
          description: "Ausgabe sortiert nach:"
        - in: query
          name: order 
          schema: 
            type: string
            default: asc
            enum:
              - asc 
              - desc
          description: |
            Sortierrichtung
            * asc - Aufsteigend A-Z
            * desc - Absteigend Z-A
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref:  "#/components/schemas/StockID"
    put:
      tags:
        - "Vorräte verwalten"
      summary: Anlegen eines neuen Vorrats.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stock"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StockID"
        "400":
          $ref: "#/components/responses/400"
        "409":
          $ref: "#/components/responses/409Stock"
  /stocks/{id}:
    patch:
      tags:
        - "Vorräte verwalten"
      summary: Änderungen eines Vorratseintrags.
      parameters:
        - name: id
          in: path
          description: Die Id des zu ändernden Vorrats
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stock"
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
        "409":
          $ref: "#/components/responses/409Stock"
    delete:
      tags:
        - "Vorräte verwalten"
      summary: Löschen eines Vorrats.
      parameters:
        - name: id
          in: path
          description: Die Id des zu löschenden Vorrats
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "204":
          $ref: "#/components/responses/204"
        "400":
          $ref: "#/components/responses/400"
        "404":
          $ref: "#/components/responses/404"
components:
  schemas:
    Box:
      type: object
      properties:
        name:
          type: string
          example: Box1
        notiz:
          type: string
          example: Notiz1
          nullable: true
    BoxID:
      allOf:
        - type: object
          properties:
            id:
              type: integer
        - $ref: "#/components/schemas/Box"
    Unit:
      type: object
      properties:
        unit:
          type: string
          example: kg
        long:
          type: string
          example: Kilogramm
          nullable: true
    UnitID:
      allOf:
        - type: object
          properties:
            id:
              type: integer
        - $ref: "#/components/schemas/Unit"
    Article:
      type: object
      properties:
        name:
          type: string
          example: Mehl
        unit:
          type: integer
          example: 1
    ArticleID:
      allOf:
        - type: object
          properties:
            id:
              type: integer
        - $ref: "#/components/schemas/Article"
    Stock:
      type: object
      properties:
        article:
          type: integer
          example: 1
        box:
          type: integer
          example: 1
        size:
          type: number
          example: 0.5
        quantity:
          type: integer
          example: 2
        expiry:
          type: string
          format: date
          example: "31.12.2021"
    StockID:
      allOf:
        - type: object
          properties:
            id:
              type: integer
              example: 1
            articlestr:
              type: string
              example: Mehl
            boxstr:
              type: string
              example: Box1
            unitstr:
              type: string
              example: kg
        - $ref: "#/components/schemas/Stock"
  responses:
    "204":
      description: No Content - Es gibt keinen Inhalt, den man für diese Anfrage senden kann, aber die Kopfzeilen können nützlich sein.
    "400":
      description: Bad Request - Diese Antwort bedeutet, dass der Server die Anfrage aufgrund einer ungültigen Syntax nicht verstehen konnte.
    "404":
      description: Not Found - Der Server kann die angeforderte Ressource nicht finden.
    "409Article":
      description: Conflict - Der Artikel verwendet eine Einheit, die nicht bekannt ist.
    "409Stock":
      description: Conflict - Der Vorratseintrag verwendet eine unbekannte Einheit, Box oder Artikel.
